env:
  matrix:
    - DEPENDENCY_MODE=libav
    - DEPENDENCY_MODE=ffmpeg

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - env | sort  
  - date -u
  - uname -a
  
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./tools/travis.linux.install.deps.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./tools/travis.osx.install.deps.sh; fi

script:
  # Build
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/install
  - make install
  # Launch tests
  - if [ "${TRAVIS_OS_NAME}" = "linux" && "${DEPENDENCY_MODE}" = "ffmpeg" ]; then ./../tools/travis.python.nosetests.sh; fi
