env:
  global:
     - AVTRANSCODER_BUILD=${TRAVIS_BUILD_DIR}/build
     - AVTRANSCODER_INSTALL=${TRAVIS_BUILD_DIR}/install
     - J='-j3'
  matrix:
    - DEPENDENCY_MODE=libav
    - DEPENDENCY_MODE=ffmpeg

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - env | sort  
  - date -u
  - uname -a

  - cd ${TRAVIS_BUILD_DIR}

  # install coverage tools
  - ./tools/travis.gcc.install.coverage.sh

  # install avtranscoder dependencies
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./tools/travis.linux.install.deps.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./tools/travis.osx.install.deps.sh; fi

script:
  # Build
  - mkdir -p ${AVTRANSCODER_BUILD}
  - cd ${AVTRANSCODER_BUILD}
  - cmake .. -DCMAKE_INSTALL_PREFIX=${AVTRANSCODER_INSTALL} -DCMAKE_BUILD_TYPE=Release -DAVTRANSCODER_PYTHON_VERSION_OF_BINDING=2.7 -DAVTRANSCODER_COVERAGE=True
  - make $J install

  # Launch tests
  - if [ "${DEPENDENCY_MODE}" = "ffmpeg" ]; then ./../tools/travis.python.nosetests.sh; fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}

  # generate coverage for coveralls
  - if [ "${CC}" = "gcc" ]; then ./tools/travis.gcc.generate.coverage.sh; fi

before_deploy:
  - cd ${AVTRANSCODER_INSTALL}
  - tar -cvzf avtranscoder_install.tgz .

deploy:
  provider: releases
  api_key:
    secure: "${GITHUB_RELEASE_API_KEY}"
  file: avtranscoder_install.tgz
  skip_cleanup: true
  on:
    tags: true

