# Use container-based infrastructure
sudo: required
services:
  - docker

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
     - AVTRANSCODER_BUILD_PATH=${TRAVIS_BUILD_DIR}/build-avtranscoder
     - AVTRANSCODER_INSTALL=install-avtranscoder
     - AVTRANSCODER_INSTALL_PATH=${TRAVIS_BUILD_DIR}/${AVTRANSCODER_INSTALL}
     - DEPENDENCY_INSTALL=install-dependency
     - DEPENDENCY_INSTALL_PATH=${TRAVIS_BUILD_DIR}/${DEPENDENCY_INSTALL}
  matrix:
    - DEPENDENCY_NAME=libav DEPENDENCY_VERSION=11.3 ENABLE_COVERAGE=true
    - DEPENDENCY_NAME=libav DEPENDENCY_VERSION=11.3 ENABLE_COVERAGE=false
    - DEPENDENCY_NAME=ffmpeg DEPENDENCY_VERSION=2.4.2 ENABLE_COVERAGE=true
    - DEPENDENCY_NAME=ffmpeg DEPENDENCY_VERSION=2.4.2 ENABLE_COVERAGE=false

matrix:
  exclude:
    # generate coverage only with gcc
    - compiler: clang
      env: DEPENDENCY_NAME=ffmpeg DEPENDENCY_VERSION=2.4.2 ENABLE_COVERAGE=true
    - compiler: clang
      env: DEPENDENCY_NAME=libav DEPENDENCY_VERSION=11.3 ENABLE_COVERAGE=true
    # generate coverage only on linux
    - os: osx
      env: DEPENDENCY_NAME=libav DEPENDENCY_VERSION=11.3 ENABLE_COVERAGE=true
    - os: osx
      env: DEPENDENCY_NAME=ffmpeg DEPENDENCY_VERSION=2.4.2 ENABLE_COVERAGE=true
  fast_finish: true

# This results in a 2×2×2x2 build matrix.
# Where the variables are: os / compiler / DEPENDENCY_NAME / ENABLE_COVERAGE

addons:
  apt:
    sources: ['kalakris-cmake']
    packages:
    - cmake
    - swig
    - python-dev
    - python-nose
    - freeglut3-dev

cache:
  # Caching Ubuntu packages
  apt: true
  # Caching other directories
  directories:
  - ${DEPENDENCY_INSTALL_PATH}

before_script:
  - env | sort
  - date -u
  - uname -a

  - cd ${TRAVIS_BUILD_DIR}

  # install coverage tools
  - if [ ${ENABLE_COVERAGE} ]; then ./tools/travis/gcc.install.coverage.sh; fi

  # install avtranscoder dependencies
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then ./tools/travis/linux.install.deps.sh; fi
  - if [ ${TRAVIS_OS_NAME} = "osx" ]; then ./tools/travis/osx.install.deps.sh; fi

script:
  # build
  - ./tools/travis/build.sh

  # launch tests
  - if [ ${TRAVIS_OS_NAME} = "linux" ] && [ ${DEPENDENCY_NAME} = "ffmpeg" ]; then ./tools/travis/python.nosetests.sh; fi

after_success:
  # generate coverage for coveralls
  - if [ ${ENABLE_COVERAGE} ]; then ./tools/travis/gcc.generate.coverage.sh; fi

before_deploy:
  # copy libbz2, external dependency of libavformat
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then cp /lib/x86_64-linux-gnu/{libbz2.so.1,libbz2.so.1.0,libbz2.so.1.0.4} ${DEPENDENCY_INSTALL_PATH}/lib; fi
  # create archive
  - cd ${TRAVIS_BUILD_DIR}
  - tar -cvzf avtranscoder-${TRAVIS_OS_NAME}-${CC}-${DEPENDENCY_NAME}-${DEPENDENCY_VERSION}.tgz ${DEPENDENCY_INSTALL} ${AVTRANSCODER_INSTALL}

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_RELEASE_API_KEY}
  file: avtranscoder-${TRAVIS_OS_NAME}-${CC}-${DEPENDENCY_NAME}-${DEPENDENCY_VERSION}.tgz
  skip_cleanup: true
  on:
    branch: master
    condition: ${ENABLE_COVERAGE} = false
