env:
  matrix:
    - DEPENDENCY_MODE=libav
    - DEPENDENCY_MODE=ffmpeg

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - env | sort  
  - date -u
  - uname -a

  - chmod +x tools/travis.linux.install.deps.sh
  - chmod +x tools/travis.osx.install.deps.sh
  
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./tools/travis.linux.install.deps.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./tools/travis.osx.install.deps.sh; fi

script:
  # Build
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/dist
  - make install
  # Launch tests
  - cd ..
  - chmod +x tools/travis.python.nosetests.sh
  - if [ "${TRAVIS_OS_NAME}" = "linux" && "${DEPENDENCY_MODE}" = "ffmpeg" ]; then ./tools/travis.python.nosetests.sh; fi

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}
  - tar -cvzf avtranscoder_install.tgz build/dist/

deploy:
  provider: releases
  api_key:
    secure: "${GITHUB_RELEASE_API_KEY}"
  file: avtranscoder_install.tgz
  skip_cleanup: true
  on:
    tags: true
