env:
  global:
     - AVTRANSCODER_BUILD=${TRAVIS_BUILD_DIR}/build-avtranscoder
     - AVTRANSCODER_INSTALL=${TRAVIS_BUILD_DIR}/install-avtranscoder
     - DEPENDENCY_INSTALL=${TRAVIS_BUILD_DIR}/install-dependency
     - CI_NODE_TOTAL=2
  matrix:
    - DEPENDENCY_MODE=libav  ENABLE_COVERAGE=true
    - DEPENDENCY_MODE=libav  ENABLE_COVERAGE=false
    - DEPENDENCY_MODE=ffmpeg ENABLE_COVERAGE=true
    - DEPENDENCY_MODE=ffmpeg ENABLE_COVERAGE=false

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - env | sort  
  - date -u
  - uname -a

  - cd ${TRAVIS_BUILD_DIR}

  # install coverage tools
  - if [ ${ENABLE_COVERAGE} ]; then ./tools/travis.gcc.install.coverage.sh; fi

  # install avtranscoder dependencies
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then ./tools/travis.linux.install.deps.sh; fi
  - if [ ${TRAVIS_OS_NAME} = "osx" ]; then ./tools/travis.osx.install.deps.sh; fi

script:
  # build
  - mkdir -p ${AVTRANSCODER_BUILD}
  - cd ${AVTRANSCODER_BUILD}
  - cmake .. -DCMAKE_INSTALL_PREFIX=${AVTRANSCODER_INSTALL} -DCMAKE_PREFIX_PATH=${DEPENDENCY_INSTALL} -DCMAKE_BUILD_TYPE=Release -DAVTRANSCODER_PYTHON_VERSION_OF_BINDING=2.7 -DAVTRANSCODER_COVERAGE=${ENABLE_COVERAGE}
  - make -j${CI_NODE_TOTAL}
  - make install

  # launch tests
  - if [ ${DEPENDENCY_MODE} = "ffmpeg" ]; then ./../tools/travis.python.nosetests.sh; fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}

  # generate coverage for coveralls
  - if [ ${ENABLE_COVERAGE} ]; then ./tools/travis.gcc.generate.coverage.sh; fi

before_deploy:
  # create archive
  - cd ${TRAVIS_BUILD_DIR}
  - tar -cvzf avtranscoder-${TRAVIS_OS_NAME}-${CC}-${DEPENDENCY_MODE}.tgz ${DEPENDENCY_INSTALL} ${AVTRANSCODER_INSTALL}

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_RELEASE_API_KEY}
  file: avtranscoder-${TRAVIS_OS_NAME}-${CC}-${DEPENDENCY_MODE}.tgz
  skip_cleanup: true
  on:
    branch: master
    condition: ${ENABLE_COVERAGE} = false
