os:
  - linux

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - date -u
  - uname -a
  - lsb_release -a
  - ln -s tools/scons.travis.cfg scons.cfg
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse"
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse"
  - sudo apt-add-repository "deb http://security.ubuntu.com/ubuntu trusty-security main restricted universe multiverse"
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc g++ scons swig swig2.0
  - sudo apt-get install -qq libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libavresample-dev python-dev freeglut3-dev doxygen

script:
  - scons

after_failure:
  - cat config.log

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "cDIO5Qhn0jjgzhgpcKMZEJf8r0Az9QQi39WL4XdKdeuYdqwXOxvh5+RfQoYUYxSZ2nPrFJqc5zXhUyGLLyqsiEOW7SCtZhBs6n1FYEFgqXiQiOHuOgj3SpIsrF5AaUkeD1tpIn/oO7QPEwfwiQptFZvmrB5tLztlX0N90rdsI6U="

addons:
  coverity_scan:
    project:
      name: "avTranscoder/avTranscoder"
      description: "[avTranscoder] Build submitted via Travis CI"
    notification_email: arnaud.marcantoine@gmail.com
    build_command_prepend: "rm -Rf build"
    build_command:   "scons -j 4"
    branch_pattern: coverity_scan
