os:
  - Windows Server 2012 R2

platform:
  - x86
#  - x64

environment:
  FFMPEG_VERSION: 2.4.5
  DEPENDENCY_INSTALL_PATH: C:\ProgramData\ffmpeg-2.4.5
  AVTRANSCODER_INSTALL_PATH: C:\projects\avtranscoder\build\install

matrix:
  fast_finish: true

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%

before_build:
  - choco install -y swig
  - tools/appveyor/win.install.deps.bat

build_script:
  - tools/appveyor/build.bat

before_test:
  - set PATH=C:\Python27\scripts;%PATH%
  - pip install nose

test_script:
  - cd ..
  - tools/appveyor/python.nosetests.bat

on_failure:
  - type "C:\ProgramData\chocolatey\logs\chocolatey.log"
  - type "C:\projects\avtranscoder\build\CMakeFiles\CMakeOutput.log"

on_success:
  - 7z a ffmpeg.zip %DEPENDENCY_INSTALL_PATH%
  - 7z a avtranscoder.zip %AVTRANSCODER_INSTALL_PATH%

artifacts:
  - path: ffmpeg.zip
    name: ffmpeg
    type: zip

  - path: avtranscoder.zip
    name: avtranscoder
    type: zip

deploy:
  - provider: GitHub
    artifact: ffmpeg,avtranscoder
    auth_token:
    secure: sApasbQe2i7Uu+XNhlkXg+F6zI0VNHUjhq5QfK6/+NSs4lX/9BwhkLvibQc6bmMv
    on:
      branch: master
      appveyor_repo_tag: true
